####################
### AUTOSTART
####################

exec-once = waybar & hypridle & hyprlock & awww-daemon & 
exec-once = wl-paste --watch cliphist store
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Flat-Remix-GTK-White-Darkest'
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
