##########################
### ENVIRONMENT VARIABLES
##########################

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = export XDG_DATA_DIRS="$HOME/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:$XDG_DATA_DIRS"


####################
### PROGRAMS
####################

# ── Apps ──────────────────────────────────────────
$terminal    = kitty
$fileManager = thunar
$menu        = rofi -show drun
$mainMod     = SUPER
$code        = code
$browser     = zen-browser
$allApps     = rofi -show drun

# ── Janelas ───────────────────────────────────────
$kill        = killactive
$fullscreen  = fullscreen, 0
$floating    = togglefloating
$altTab      = cyclenext

# ── Sistema ───────────────────────────────────────
$lock        = hyprlock
$wallpaper   = ~/.config/hypr/scripts/nextwallpaper.sh
$btop        = $terminal -e btop
$print       = ~/.config/hypr/scripts/print.sh
$record      = ~/.config/hypr/scripts/record.sh
$1080        = hyprctl keyword monitor ,1920x1080@144,auto,1
$1440        = hyprctl keyword monitor ,3440x1440@144,auto,1

# ── Volume (SUPER + setas) ────────────────────────
$soundUp     = pactl set-sink-volume @DEFAULT_SINK@ +5%
$soundDown   = pactl set-sink-volume @DEFAULT_SINK@ -5%
$soundMute   = pactl set-sink-mute @DEFAULT_SINK@ toggle
$changeSoundOutput = ~/.config/hypr/scripts/toggleaudio.sh

# ── Rofi ──────────────────────────────────────────
$rofi        = ~/.config/hypr/scripts/rofi-menu.sh
